[versions]
agp = "8.4.2"
androidBasic = "1.6.5"
coreKtx = "1.10.0"
deviceToolkit = "2.0.2"
fileToolkit = "1.1.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
multiDex = "2.0.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
kotlin = "1.8.22"
kapt = "1.8.22"
taskBeehive = "2.0.1"
androidautosize = "v1.2.1"
immersionbar = "3.2.2"

[libraries]
android-basic = { module = "com.github.starseaway:android-basic", version.ref = "androidBasic" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
device-toolkit = { module = "com.github.starseaway:device-toolkit", version.ref = "deviceToolkit" }
file-toolkit = { module = "com.github.starseaway:file-toolkit", version.ref = "fileToolkit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multiDex" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
task-beehive = { module = "com.github.starseaway:task-beehive", version.ref = "taskBeehive" }
androidautosize = { module = "com.github.JessYanCoding:AndroidAutoSize", version.ref = "androidautosize" }
immersionbar = { module = "com.geyifeng.immersionbar:immersionbar", version.ref = "immersionbar" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }